# Generated by Django 5.0.6 on 2024-07-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_pedido_tarjetapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
